package fr.neatmonster.nocheatplus.hooks.violationfrequency;

import fr.neatmonster.nocheatplus.config.ConfPaths;
import fr.neatmonster.nocheatplus.config.ConfigFile;

/**
 * Configuration for the ViolationFrequencyHook.
 *
 * @author xaw3ep
 *
 */

public class ViolationFrequencyConfig {
    /** Set this hook active or not */
    protected final boolean active;

    /** Log whenever more vls is added */
    protected final boolean debug;

    /** 
     * The amount to add to the VL generated by the check that is considered too small.
     * (Under "maxThresholdVL" not higher than "noAdditionVL")
     */
    protected final int amountToAdd;

    /** Move count from the last violated move. */
    protected final int lastViolatedMoveCount;

    /** 
     * Minimum violation value under "maxTreshold", for which the hook won't add the "amountToAdd" amount.
     * i.e.: max threshold 15, noAdditionVL 6 and the violation is 7. The violation will not be increased because it's high enough already.
     */
    protected final int noAdditionVL;

    /** Violations higher than the maximum threshold won't use this hook. (thus won't increase the VL) */
    protected final int maxThresholdVL;

    public ViolationFrequencyConfig(ConfigFile config) {
        active = config.getBoolean(ConfPaths.MOVING_SURVIVALFLY_VLFREQUENCY_ACTIVE);
        debug = config.getBoolean(ConfPaths.MOVING_SURVIVALFLY_VLFREQUENCY_DEBUG);
        amountToAdd = config.getInt(ConfPaths.MOVING_SURVIVALFLY_VLFREQUENCY_AMOUNTTOADD);
        noAdditionVL = config.getInt(ConfPaths.MOVING_SURVIVALFLY_VLFREQUENCY_NOADDITIONVL);
        maxThresholdVL = config.getInt(ConfPaths.MOVING_SURVIVALFLY_VLFREQUENCY_MAXTHRESHOLDVL);
        lastViolatedMoveCount = config.getInt(ConfPaths.MOVING_SURVIVALFLY_VLFREQUENCY_LASTVIOLATEDMOVECOUNT);
    }
    //public ViolationFrequencyConfig() {
    //    active = true;
    //    debug = true;
    //    morevls = 5;
    //  minaddedvls = 5;
    //  maxtotalvls = 35; 
    //  movecount = 10;
    //}
}
